## 'invs' is assigned to 'NULL' in the environment of 'makecacheMatrix function'.
## The "set function(y)' is defined thereby assigning it to the matrix x using the "<<" operator.
## invs is also assigned to 'NULL' using the "<<" operator
## The get function() is defined to fearch the matrix x
## The inverse of the matrix is generated by the 'setinves function'. This assigns 'inverse' using the "<<" operator to 'invs'
## The 'getinves function' then gets the 'invs'
## list is created

makeCacheMatrix <- function(x = matrix()) {
        invs <- NULL
        set <- function(y)
                {
                x <<- y
                invs <<- NULL
                }
        
        get <- function ()x
                setinves <- function (inverse) invs <<- inverse
                getinves <- function () invs
        list(set = set, get = get, setinves = setinves, getinves = getinves)

}


## Get the inverse of the function in x using "$" operator
## The value of 'invs' if not 'NULL', the data in the Cache is returned.
## The invs is generated by 'get()' getting the underlying matrix and the inverse calculated on it.
## The inverse is then set to 'invs'

cacheSolve <- function(x, ...) {
        
        invs <- x$getinves()
        if (!is.null(invs))
                {
                  message("getting Cached data")
                  return(invs)
                }
        data <- x$get()
        invs <- solve(data,...)
        x$setinves(invs)
        invs
}
